Mat laplacian(Mat img);
Mat sobelx(Mat img);
Mat sobely(Mat img);
Mat edges(Mat img);
Mat lowerReso(Mat img);
Mat higherReso(Mat img);
vector<vector<Point>> contours(Mat img);
Mat imageContours(Mat img);
void contoursInfo(Mat img);
